// CHARACTER/HitmBridge/HitmMoveInstance.h
// ROADMAP.md Track H Module 5A -- CPU-observable HITM runtime vertical
// slice. Extracts one real, authored move from a fighter's real
// signature.json (already imported losslessly by Module 1 as
// HitmIdentityRecord::signature) into COMBAT's own existing
// `dominus::combat::MoveDef` type wherever its shape genuinely fits, plus
// the real fields signature.json has that MoveDef does not model.
//
// A REAL FINDING, not asserted: signature.json's top-level "moves" object
// (blockbuster/maniac/special/specialF/throw/throwF for Brooklyn) contains
// zero basic normals -- no "jab", no "light1/2/3" (the IDs
// `signature.json`'s own "chains.light" array references). Those are
// generated by HITM's `genome_compiler.py` from `character_dna.json` +
// `archetype_rules.json`, not hand-authored, and neither this module nor
// any prior Track H module imports that generated output. This vertical
// slice therefore drives Brooklyn's real "special" move (input token "S",
// fully authored: startup/active/recovery/damage/hitstun/blockstun/
// meterGain/hitstop/range/height/cooldown) -- it does NOT invent a "jab"
// or "light attack" to fill the gap. See HITM_FIGHTER_RUNTIME_REPORT.md
// for the full architectural-gap accounting.
//
// A SECOND REAL FINDING, caught by running the test suite against all
// three real fighters rather than assumed from Brooklyn alone: real
// signature.json move schemas are NOT uniform across fighters or move
// types. Brooklyn's "special" has every field this extractor requires.
// Rocket's real "special" ("Ghost Dash") has no `blockstun` and no flat
// `range`/`height` at all -- it is a "rush"-type move with a `rush`
// sub-object (`velocityX`/`friction`/`hitRangeX`/`hitRangeY`) instead.
// Static's real "special" ("Live Wire") has `range`/`height` but no
// `blockstun` and no `hitstop`. This extractor's required-field set is
// therefore only evidenced for Brooklyn-shaped kick/strike specials, not
// a general contract every fighter's "special" satisfies -- it correctly
// refuses Rocket's and Static's real specials (see
// tests/character/test_hitm_move_instance.cpp's Break_ tests) rather
// than silently defaulting their missing fields. A real move importer
// covering every fighter would need per-move-TYPE schemas (kick/rush/
// projectile/...), which is real, separately-scoped future work, not
// attempted here.
//
// FIELDS MoveDef HAS THAT THIS EXTRACTOR DOES NOT POPULATE, documented
// rather than silently defaulted: `motion_trigger` (real HITM has no
// MotionGraphEvaluator-shaped state graph -- see HitmFighterRuntime.h's
// top comment for why), `hitboxes` (real HITM hit reach is a flat
// range/height pair, not bone-relative circles -- captured separately
// below as `range`/`height`, not force-fit into HitboxDef), `speed`
// (moveDef's own concept, no real HITM equivalent found), `frames.
// hit_advantage`/`frames.block_advantage` (computable from hitstun/
// recovery by a real formula, but the exact convention isn't itself
// authored data -- deferred rather than guessed).
#pragma once

#include <string>

#include "CHARACTER/HitmBridge/HitmIdentityRecord.h"
#include "COMBAT/HitSystem/MoveDef.h"
#include "CORE/Serialization/DominusSerializer.h"  // for core::Result<T>

namespace dominus::character::hitm {

enum class HitmHitstopCategory { kLight, kHeavy, kCounter };

struct HitmMoveInstance {
    std::string move_key;      // the real key under signature.json's "moves", e.g. "special"
    combat::MoveDef move_def;  // real: name, frames.{startup,active,recovery}, power (== authored "damage")
    std::string input_token;   // real "input" field, e.g. "S"
    int hitstun_frames = 0;
    int blockstun_frames = 0;
    int meter_gain = 0;
    HitmHitstopCategory hitstop_category = HitmHitstopCategory::kLight;
    double range = 0;
    double height = 0;
    int cooldown_frames = 0;

    // Reads real-fighting-game/data/identity/<fighter>/signature.json's
    // moves.<moveKey> from an already-imported, already-validated
    // HitmIdentityRecord (Module 1). Fails (Result::Fail) on a missing
    // move key or any required field missing/wrong-typed -- never a
    // partial or defaulted MoveDef.
    static core::Result<HitmMoveInstance> Extract(const HitmIdentityRecord& record, const std::string& moveKey);
};

}  // namespace dominus::character::hitm
